<html>
<head>
<style>
body 
 {
  background: url("https://www.indcareer.com/events/wp-content/uploads/2019/07/Coimbatore-Institute-of-Technology.png");
  background-size: 100%;
  background-repeat: no-repeat;
  }
  form
  {
  width: 30%;
  box-sizing: border-box;
  border: solid #DB7093;
  background-color: #FFF0F5;
  color: black;
  }
</style>
</head>
<body>
<center>
<pre>
<font face="calibri" size="8">Coimbatore Institute of Technology</font>
<font face="calibri" size="6">Student MARKSHEET Generation</font>

<form action="5-result.php">
<b><font face="calibri" size="4">
Enter Register No   <input type=text name=rno size=20>

  <input type=submit>        <input type=reset>
</font></b>
</form></pre></center>
</body>
</html>