<html>
<head>
<style>
body {
    background: url("https://www.indcareer.com/events/wp-content/uploads/2019/07/Coimbatore-Institute-of-Technology.png");
    background-size: 100%;
    background-repeat: no-repeat;
  }
  form
  {
  width: 30%;
  box-sizing: border-box;
  border: solid #DB7093;
  background-color: #FFF0F5;
  color: black;
  }
</style>
</head>
<body>
<font face="calibri" size="7">Coimbatore Institute of Technology</font><br>
<form action="4-result.php">
<pre>
<font face="calibri" size="5">    Student Marks Entry Form</font>
<font face="calibri" size="3">
     Register No        <input type=text name=rno size=20>

     Student Name   <input type=text name=name size=20>

     Semester           <input type=text name=sem size=20>

     Gender         <input type=radio name=gen size=20 value="Male">Male    <input type=radio name=gen size=30 value="Female">Female

               Enter Marks for the subjects
     Data Structures                                  <input type=text name=ds size=10>

     Database Management Systems     <input type=text name=dbms size=10>

     Data Communicatiosn                      <input type=text name=dc size=10>

     Operating Systems                            <input type=text name=os size=10>

     Microprocessors			          <input type=text name=mp size=10>
	
	                <input type=submit>         <input type=reset>
</font>
</pre>
</form>
</body>
</html>